name: ROS2 CI

on:
  pull_request:
    branches:
      - 'devel'
      - 'master'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - dashing
          - eloquent
          - foxy
          - rolling
        include:
          # Dashing Diademata (May 2019 - May 2021)
          - os: ubuntu
            os_release: bionic
            ros_distribution: dashing
            ros_version: 2
          # Eloquent Elusor (November 2019 - November 2020)
          - os: ubuntu
            os_release: bionic
            ros_distribution: eloquent
            ros_version: 2
          # Foxy Fitzroy (June 2020 - May 2023)
          - os: ubuntu
            os_release: focal
            ros_distribution: foxy
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - os: ubuntu
            os_release: focal
            ros_distribution: rolling
            ros_version: 2
    container:
      image: '${{ matrix.os }}:${{ matrix.os_release }}'
    steps:
      - name: install prereqs
        run: apt update && apt install -y sudo curl wget
      - name: download eCAL
        run: |
          curl -L -o ecal.deb $(curl -s https://api.github.com/repos/continental/ecal/releases/latest \
          | grep "${{ matrix.os_release }}_amd64.deb" \
          | tr -d '\n' | tr -d '\r' \
          | cut -d'"' -f8)
      - name: install eCAL bionic dependencies
        if: matrix.os_release == 'bionic'
        run: 'sudo apt install -y libc6 libcurl4 libgcc1 libhdf5-100 libqt5core5a libqt5gui5 libqt5widgets5 libstdc++6'
      - name: install eCAL focal dependencies
        if: matrix.os_release == 'focal'
        run: 'sudo apt install -y libc6 libcurl4 libgcc1 libhdf5-103 libqt5core5a libqt5gui5 libqt5widgets5 libstdc++6'
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@0.0.26
        with:
          use-ros2-testing: false
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: rosdep install
        run: "rosdep update && rosdep install -r --from-paths ros_ws/src --ignore-src --rosdistro ${{ matrix.ros_distribution }} -y"
      - name: install eCAL deb
        run: 'sudo dpkg -i ecal.deb'
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.1.0
        with:
          package-name: rmw_ecal_dynamic_cpp
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
