name: ROS2 CI

on:
  pull_request:
    branches:
      - 'devel'
      - 'master'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - dashing
          - eloquent
          - foxy
          - rolling
        include:
          # Dashing Diademata (May 2019 - May 2021)
          - os: ubuntu
            os_release: bionic
            ros_distribution: dashing
            ros_version: 2
          # Eloquent Elusor (November 2019 - November 2020)
          - os: ubuntu
            os_release: bionic
            ros_distribution: eloquent
            ros_version: 2
          # Foxy Fitzroy (June 2020 - May 2023)
          - os: ubuntu
            os_release: focal
            ros_distribution: foxy
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - os: ubuntu
            os_release: focal
            ros_distribution: rolling
            ros_version: 2
    container:
      image: '${{ matrix.os }}:${{ matrix.os_release }}'
    steps:
      - name: install sudo
        run: apt update && apt install sudo
      - name: download eCAL
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "continental/ecal"
          version: "latest"
          file: "ecal-${{ matrix.os_release }}.deb"
      - name: install eCAL dependencies
        run: 'sudo apt install libc6 libcurl4 libgcc1 libhdf5-100 libprotobuf10 libqt5core5a libqt5gui5 libqt5widgets5 libstdc++6'
      - name: install eCAL deb
        run: 'sudo dpkg -i ecal-${{ matrix.os_release }}.deb'
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: setup ROS environment
        uses: flynneva/setup-ros@enable_ros2_testing
        with:
          use-ros2-testing: true
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.0.19
        with:
          package-name: rmw_ecal_dynamic_cpp
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
